name: CI
on: [push]
jobs:
  nextlint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Install packages
       run: npm ci
     - name: Run Next Lint
       run: npm run lint 
  
